name: domain_driven
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
  fonts:
    - family: circular
      fonts:
        - asset: assets/fonts/circular-std-2.ttf